CREATE TABLE [dbo].[ZIGLOG](
	[ZIGLOGCOD] [int] IDENTITY(1,1) NOT NULL,
	[ZIGLOGEST] [char](10) NOT NULL,
    [ZIGLOGFEC] [date] NOT NULL,
    [ZIGLOGCOR] [varchar](100) NOT NULL,
    [ZIGLOGPAS] [varchar](MAX) NOT NULL,
    [ZIGLOGDIP] [varchar](100) NOT NULL,
    [ZIGLOGHOS] [varchar](250) NOT NULL,
    [ZIGLOGAGE] [varchar](MAX) NOT NULL,
	[ZIGLOGREF] [varchar](MAX) NOT NULL,
	[ZIGLOGAUS] [char](20) NOT NULL,
	[ZIGLOGAFH] [datetime] NOT NULL,
	[ZIGLOGAIP] [char](20) NOT NULL,
 CONSTRAINT [PK_ZIGLOGCOD] PRIMARY KEY CLUSTERED ([ZIGLOGCOD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

CREATE TABLE [aud].[ZIGLOG](
	[ZIGLOGIDD] [int] IDENTITY(1,1) NOT NULL,
	[ZIGLOGAME] [char](20) NOT NULL,
	[ZIGLOGAUS] [char](20) NOT NULL,
	[ZIGLOGAFH] [datetime] NOT NULL,
	[ZIGLOGAIP] [char](20) NOT NULL,
	[ZIGLOGCOD] [int],
	[ZIGLOGEST] [char](10),
    [ZIGLOGFEC] [date],
    [ZIGLOGCOR] [varchar](100),
    [ZIGLOGPAS] [varchar](MAX),
    [ZIGLOGDIP] [varchar](100),
    [ZIGLOGHOS] [varchar](250),
    [ZIGLOGAGE] [varchar](MAX),
	[ZIGLOGREF] [varchar](MAX),
 CONSTRAINT [PK_ZIGLOGIDD] PRIMARY KEY CLUSTERED ([ZIGLOGIDD] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]) ON [PRIMARY]
GO

CREATE TRIGGER [dbo].[ZIGLOG_INSERT] 
	ON [dbo].[ZIGLOG]
	AFTER INSERT
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [aud].[ZIGLOG] (ZIGLOGAME, ZIGLOGAUS, ZIGLOGAFH, ZIGLOGAIP, ZIGLOGCOD, ZIGLOGEST, ZIGLOGFEC, ZIGLOGCOR, ZIGLOGPAS, ZIGLOGDIP, ZIGLOGHOS, ZIGLOGAGE, ZIGLOGREF)
		SELECT 'INSERT AFTER', i.ZIGLOGAUS, GETDATE(), i.ZIGLOGAIP, i.ZIGLOGCOD, i.ZIGLOGEST, i.ZIGLOGFEC, i.ZIGLOGCOR, i.ZIGLOGPAS, i.ZIGLOGDIP, i.ZIGLOGHOS, i.ZIGLOGAGE, i.ZIGLOGREF FROM INSERTED i;
	END
GO

CREATE TRIGGER [dbo].[ZIGLOG_UPDATE] 
	ON [dbo].[ZIGLOG]
	AFTER UPDATE
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [aud].[ZIGLOG] (ZIGLOGAME, ZIGLOGAUS, ZIGLOGAFH, ZIGLOGAIP, ZIGLOGCOD, ZIGLOGEST, ZIGLOGFEC, ZIGLOGCOR, ZIGLOGPAS, ZIGLOGDIP, ZIGLOGHOS, ZIGLOGAGE, ZIGLOGREF)
		SELECT 'UPDATE BEFORE', d.ZIGLOGAUS, GETDATE(), d.ZIGLOGAIP, d.ZIGLOGCOD, d.ZIGLOGEST, d.ZIGLOGFEC, d.ZIGLOGCOR, d.ZIGLOGPAS, d.ZIGLOGDIP, d.ZIGLOGHOS, d.ZIGLOGAGE, d.ZIGLOGREF FROM DELETED d;

		INSERT INTO [aud].[ZIGLOG] (ZIGLOGAME, ZIGLOGAUS, ZIGLOGAFH, ZIGLOGAIP, ZIGLOGCOD, ZIGLOGEST, ZIGLOGFEC, ZIGLOGCOR, ZIGLOGPAS, ZIGLOGDIP, ZIGLOGHOS, ZIGLOGAGE, ZIGLOGREF)
		SELECT 'UPDATE AFTER', i.ZIGLOGAUS, GETDATE(), i.ZIGLOGAIP, i.ZIGLOGCOD, i.ZIGLOGEST, i.ZIGLOGFEC, i.ZIGLOGCOR, i.ZIGLOGPAS, i.ZIGLOGDIP, i.ZIGLOGHOS, i.ZIGLOGAGE, i.ZIGLOGREF FROM INSERTED i;
	END
GO

CREATE TRIGGER [dbo].[ZIGLOG_DELETE] 
	ON [dbo].[ZIGLOG]
	AFTER DELETE
	AS
	BEGIN
		SET NOCOUNT ON;
		INSERT INTO [aud].[ZIGLOG] (ZIGLOGAME, ZIGLOGAUS, ZIGLOGAFH, ZIGLOGAIP, ZIGLOGCOD, ZIGLOGEST, ZIGLOGFEC, ZIGLOGCOR, ZIGLOGPAS, ZIGLOGDIP, ZIGLOGHOS, ZIGLOGAGE, ZIGLOGREF)
		SELECT 'DELETE BEFORE', d.ZIGLOGAUS, GETDATE(), d.ZIGLOGAIP, d.ZIGLOGCOD, d.ZIGLOGEST, d.ZIGLOGFEC, d.ZIGLOGCOR, d.ZIGLOGPAS, d.ZIGLOGDIP, d.ZIGLOGHOS, d.ZIGLOGAGE, d.ZIGLOGREF FROM DELETED d;
	END
GO